import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { sessionPromptHistory } from '../lib/api.js';

const ATTACHMENT_RE =
  /"[^"]*[\\/]uploads[\\/]att-\d+-\d+\.[a-z0-9]+"|\S*[\\/]uploads[\\/]att-\d+-\d+\.[a-z0-9]+|\[attachment\]/gi;
const INJECTED_RE = [/^base directory for this skill:/i, /^caveat: the messages below were generated by the user/i, /^\[request interrupted/i, /^<[a-z-]+>/i];

export function visiblePromptText(text) {
  const value = String(text || '').replace(ATTACHMENT_RE, ' ').replace(/\s+/g, ' ').trim();
  return INJECTED_RE.some((pattern) => pattern.test(value)) ? '' : value;
}

export default function PromptHistoryBar({ session, active, onHide }) {
  const [messages, setMessages] = useState([]);
  const [promptIdx, setPromptIdx] = useState(null);

  const prompts = useMemo(() => messages
    .filter((message) => message.role === 'user' && !message.injected && message.text)
    .map((message) => visiblePromptText(message.text))
    .filter(Boolean), [messages]);
  const at = promptIdx == null ? prompts.length - 1 : Math.min(promptIdx, prompts.length - 1);
  const prompt = prompts[at] || '';

  const refresh = useCallback(() => {
    if (!active) return;
    sessionPromptHistory(session.id)
      .then(({ messages: fresh = [] }) => setMessages(fresh))
      .catch(() => {});
  }, [active, session.id]);

  useEffect(() => {
    setMessages([]);
    setPromptIdx(null);
  }, [session.id]);

  useEffect(() => {
    if (!active) return undefined;
    refresh();
    const timer = setInterval(refresh, 4000);
    const onVisible = () => { if (document.visibilityState === 'visible') refresh(); };
    document.addEventListener('visibilitychange', onVisible);
    window.addEventListener('focus', refresh);
    return () => {
      clearInterval(timer);
      document.removeEventListener('visibilitychange', onVisible);
      window.removeEventListener('focus', refresh);
    };
  }, [active, refresh]);

  return (
    <div className="prompt-history" aria-live="polite">
      <button
        type="button"
        className="prompt-history-nav"
        onClick={() => setPromptIdx(Math.max(0, at - 1))}
        disabled={at <= 0}
        aria-label="Earlier prompt"
      >
        ‹
      </button>
      <button type="button" className="prompt-history-body" onClick={onHide} title="Hide prompt history">
        <span className="prompt-history-mark">❯</span>
        <span className={'prompt-history-text' + (!prompt ? ' empty' : '')}>
          {prompt || 'No user prompts recorded yet'}
        </span>
        {prompts.length > 1 && <span className="prompt-history-count">{at + 1}/{prompts.length}</span>}
      </button>
      <button
        type="button"
        className="prompt-history-nav"
        onClick={() => setPromptIdx(at + 1 >= prompts.length - 1 ? null : at + 1)}
        disabled={at >= prompts.length - 1}
        aria-label="Later prompt"
      >
        ›
      </button>
    </div>
  );
}
