import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { cleanPrompt, parseMessages, toolLabel } from '../src/services/transcript.js';

// One assistant turn that narrates, runs two tools, then answers — the shape the
// chat view has to show while it is still running.
const TURN = [
  { type: 'user', message: { role: 'user', content: 'fix the build' } },
  {
    type: 'assistant',
    message: {
      content: [
        { type: 'thinking', thinking: '', signature: 'abc' }, // always stripped on disk
        { type: 'text', text: 'Looking into it.' },
        { type: 'tool_use', name: 'Read', input: { file_path: 'C:\\AI\\x\\ChatView.jsx' } },
      ],
    },
  },
  { type: 'user', message: { role: 'user', content: [{ type: 'tool_result', content: 'ok' }] }, toolUseResult: {} },
  {
    type: 'assistant',
    message: {
      content: [
        { type: 'tool_use', name: 'Bash', input: { command: 'npm run build', description: 'Rebuild the bundle' } },
        { type: 'text', text: 'Fixed.' },
      ],
    },
  },
];

function writeTranscript(lines) {
  const dir = mkdtempSync(join(tmpdir(), 'cvh-conv-'));
  const path = join(dir, 't.jsonl');
  writeFileSync(path, lines.map((l) => JSON.stringify(l)).join('\n'));
  return path;
}

test('a tool call is labelled by what it acted on, not its raw arguments', () => {
  assert.equal(toolLabel('Read', { file_path: 'C:\\AI\\x\\ChatView.jsx' }), 'Read: ChatView.jsx');
  // A description beats the command: it is what the step is FOR.
  assert.equal(toolLabel('Bash', { command: 'npm run build', description: 'Rebuild' }), 'Bash: Rebuild');
  assert.equal(toolLabel('Grep', { pattern: 'foo' }), 'Grep: foo');
  assert.equal(toolLabel('Read', {}), 'Read'); // nothing worth appending
});

// The archive indexer and the resume backfill write parseMessages' rows straight
// into a table that only knows user/assistant, so steps must stay opt-in.
test('tool calls stay out of the transcript parse unless asked for', async () => {
  const rows = await parseMessages(writeTranscript(TURN));
  assert.deepEqual(rows.map((r) => r.role), ['user', 'assistant', 'assistant']);
  assert.equal(rows.some((r) => r.role === 'activity'), false);
});

test('steps mode emits tool calls in order, between the text around them', async () => {
  const rows = await parseMessages(writeTranscript(TURN), { steps: true });
  assert.deepEqual(
    rows.map((r) => `${r.role}:${r.text}`),
    [
      'user:fix the build',
      'assistant:Looking into it.',
      'activity:Read: ChatView.jsx',
      'activity:Bash: Rebuild the bundle',
      'assistant:Fixed.',
    ]
  );
});

// An empty `thinking` block (all the transcript ever holds) must not become a bubble.
test('stripped thinking blocks never reach the conversation', async () => {
  const rows = await parseMessages(writeTranscript(TURN), { steps: true });
  assert.equal(rows.some((r) => r.text === ''), false);
});

// Claude Code writes injected content — a skill body it loads mid-turn, the
// local-command caveat — as role "user" with isMeta. Those are not things the
// person typed, and surfacing them as such put a skill's preamble in the phone's
// "your last prompt" pill.
test('injected meta turns are not mistaken for what the user typed', async () => {
  const path = writeTranscript([
    { type: 'user', message: { role: 'user', content: 'fix the build' }, origin: { kind: 'human' } },
    { type: 'user', isMeta: true, message: { role: 'user', content: 'Base directory for this skill: /tmp/skills/x' } },
    { type: 'user', isMeta: true, message: { role: 'user', content: 'Caveat: The messages below were generated by the user' } },
    { type: 'assistant', message: { content: [{ type: 'text', text: 'On it.' }] } },
    { type: 'user', message: { role: 'user', content: 'now run the tests' } },
  ]);
  const messages = await parseMessages(path);
  assert.deepEqual(
    messages.filter((m) => m.role === 'user').map((m) => m.text),
    ['fix the build', 'now run the tests']
  );
});

test('a transcript with no origin field still yields its user prompts', async () => {
  // Older Claude Code stamped neither origin nor promptSource — absence there
  // must not be read as "injected", or history would empty out entirely.
  const path = writeTranscript([{ type: 'user', message: { role: 'user', content: 'older client prompt' } }]);
  const [message] = await parseMessages(path);
  assert.equal(message.text, 'older client prompt');
  assert.equal(message.injected, undefined);
});

// The composer swaps a `[label]` token for the real uploads path so Claude can
// read the file; only the display copy should be turned back into something human.
test('an attached file reads as an attachment, not a temp path', () => {
  const winPath = String.raw`"C:\Users\karan\.claude-voice-harness\uploads\att-1786826206170-3.jpg"`;
  assert.equal(cleanPrompt(`look at this ${winPath}`), 'look at this [attachment]');
  assert.equal(
    cleanPrompt('/home/k/.claude-voice-harness/uploads/att-17868-1.png explain it'),
    '[attachment] explain it'
  );
  assert.equal(cleanPrompt(`two ${winPath} ${winPath}`), 'two [attachment] [attachment]');
});

test('a path the user actually typed survives', () => {
  assert.equal(cleanPrompt('open C:/AI/voice harness/README.md'), 'open C:/AI/voice harness/README.md');
  assert.equal(cleanPrompt('check uploads/att-notes.txt'), 'check uploads/att-notes.txt');
});
