// Your prompt as YOU typed it. Attaching a file rewrites your `[label]` token
// into the absolute upload path before the message is sent, so the stored prompt
// carries a path you never wrote — the harness turns that into "[attachment]",
// and both forms are stripped here (the raw path too, so this reads correctly
// against a harness that predates that change). A prompt that was nothing but an
// attachment has no words to show and comes back empty for the caller to drop.
const ATTACHMENT_RE =
  /"[^"]*[\\/]uploads[\\/]att-\d+-\d+\.[a-z0-9]+"|\S*[\\/]uploads[\\/]att-\d+-\d+\.[a-z0-9]+|\[attachment\]/gi;

// Content the CLI writes as a user turn but you never typed. The harness marks
// these structurally (`isMeta` in the transcript), which is the real fix — this
// list is the bridge for a harness process that predates it, the same way the
// terminal renderer copes with a server that still sends pre-linkified HTML.
// Anchored at the start so a prompt that MENTIONS one of these still counts.
const INJECTED_RE = [
  /^base directory for this skill:/i, // a skill Claude loaded mid-turn
  /^caveat: the messages below were generated by the user/i, // local-command preamble
  /^\[request interrupted/i,
  /^<[a-z-]+>/i, // any tag-led injection the server didn't strip
];

export function promptText(text) {
  const value = String(text || '').replace(ATTACHMENT_RE, ' ').replace(/\s+/g, ' ').trim();
  return INJECTED_RE.some((pattern) => pattern.test(value)) ? '' : value;
}

// Shared merge for the conversation delta both pollers use (chat view, terminal
// history). The server sends the tail from the client's cursor onward — starting
// AT that cursor, because a streaming answer keeps its id while its text grows —
// so everything from the tail's first id is replaced wholesale and the rest of
// the held list is left alone.
export function mergeTail(held, tail) {
  if (!tail || !tail.length) return held;
  const from = Number(tail[0].id);
  return [...held.filter((message) => Number(message.id) < from), ...tail];
}
